### ISSUE TITLE
Expanded macro definition is shown on compilation

### ISSUE THREAD

**Issue by tlockney** [storm-enroute/coroutines#10]
When I set up a simple project and define a coroutine either in a source file or at the Scala console, I see the expanded macro code dumped out upon compilation. I'm not sure what might be responsible for this, as I'm not setting any compiler flags, so my only guess is that this is due to something that was set at the time the library was built. If this is intended behavior, it might be good to document it (maybe it is and I just missed it). 

As an example, building the following code from the Getting Started Guide

```scala
import scala.coroutines._ 
object Identity {
  val id = coroutine { (x: Int) => x }
 
  def main(args: Array[String]) {
    val c = call(id(7))
    assert(!c.resume)
    assert(c.result == 7)
  }
}
```

results in the following output (truncated for brevity) as soon as it's compiled (or immediately after entering the `coroutine` line in the console):

```
{
  final class $anon extends scala.coroutines._1$spec$I[Nothing, Int] {
...
}
```

**Comment by tlockney** [comment]
Nevermind, found the source of this behavior after a quick glance at the code. Thought it was some kind of magic I wasn't understanding rather than a very obvious println I would have seen on inspection. ;~)

**Comment by axel22** [comment]
Yep - was just an overlooked `println`.
