### ISSUE TITLE
Misuse of the scala namespace

### ISSUE THREAD

**Issue by milessabin** [storm-enroute/coroutines#12]
This project is an ordinary Scala library. It doesn't require any special support from the Scala compiler or runtime, so there's no justification for it being in the `scala` namespace.

**Comment by SethTisue** [comment]
I tend to agree. note that general discussion on this question is at https://github.com/scala/slip/issues/31 . I've commented there as well.

**Comment by axel22** [comment]
I don't have a strong opinion about this, but now that I see the discussion for SLIP 31, I guess it makes sense.
Any suggestions for the package name?

**Comment by SethTisue** [comment]
this got discussed and settled (against using `scala.` for anything but the standard library) at https://contributors.scala-lang.org/t/should-the-scala-platform-modules-use-the-scala-namespace/422/6

**Comment by axel22** [comment]
Thanks for the heads-up! At the moment, I think the issue is fixed - there should be no more uses of the `scala.` package prefix in this codebase (as far as I know).
