### ISSUE TITLE
Recursive coroutines terminate early

### ISSUE THREAD

**Issue by chris-martin** [storm-enroute/coroutines#14]
It seems that a coroutine containing a recursive call terminates as soon as the first recursive call returns.

One example:

```
val foo: Int ~~> (Int, Unit) = coroutine { (i: Int) =>
  yieldval(i)
  if (i > 0) { foo(i - 1); foo(i - 1) }
}

val bar = coroutine { () => foo(2); foo(2) }

val c = call(bar())
while (c.resume) print(c.value)
```

Expected output: `211211`

Actual output: `21`

Scala 2.11.7, coroutines 0.4.

**Comment by axel22** [comment]
Many thanks for reporting!!

Actually, expected output is `21001002100100`. ^_^

The actual output is indeed `21`. This happens due to an `ArrayIndexOutOfBoundsException`, which means it's easy to fix (it's not a transformation error, phew!). Fix took only 4 characters :)

**Comment by chris-martin** [comment]
Very speedy fix :smile_cat:
