### ISSUE TITLE
Limit to coroutine calls within coroutine

### ISSUE THREAD

**Issue by IMakeGames** [storm-enroute/coroutines#21]
Hi!

There seems to be a hard limit to how many coroutine calls can be inside a coroutine. Consider the following example:
```
package test

import org.coroutines.Coroutine
import org.coroutines.Coroutine
import org.coroutines.call
import org.coroutines.coroutine
import org.coroutines.yieldval


val test = coroutine { () => {}}
val foo = coroutine { () => {
      test()
      test()
      test()
      test()
      test()
      test()
      test()
      test()
      test()
      test()
      test()
      test()
      test()
      test()
      test()
      test()
      test()
      test()
      test()
      test()
      test()
      test()
      test()
      test()
      test()
      test()
      test()
      test()
      test()
      //test() uncommenting this line does not compile
  }}

```

The limit for calling coroutines is exactly 30 when calling them "plain". Strangely enough however, the limit seems to change when loops are used:

```
val test = coroutine { () => {}}
val foo = coroutine { () => {
    do {
      test()
      test()
      test()
      test()
      test()
      test()
      test()
      test()
      test()
      test()
      test()
      test()
      test()
      test()
      //test() uncommenting this line does not compile
    } while (true);
  }}
```

**Comment by axel22** [comment]
Hey, can you tell me which versions of coroutines you're using?

**Comment by IMakeGames** [comment]
Using 2.11-0.6
Relevant gradle line:
`compile group: 'com.storm-enroute', name: 'coroutines_2.11', version: '0.6'`

**Comment by axel22** [comment]
Thanks a lot. This issue should be fixed in `0.7-SNAPSHOT`:

https://github.com/storm-enroute/coroutines/commit/6ccb801ff81a27e2d5d5c68d415fbb27579794f1

Unfortunately, the fix did not make it into `0.6` version. Would using the snapshot for the time being be an option for you?

**Comment by IMakeGames** [comment]
Thank you for taking the time to look into this! :) I saw your fix, but does that really fix it though? What if I have more than 40 coroutine calls? It looks like making this number dynamic would require a lot of work (or not?). Is there any significant drawback to just setting this to a high(er) number? Like, I dunno... 500? So that the chance to run into this is really tiny? Because I can see myself easily surpassing 40 coroutine calls.

**Comment by axel22** [comment]
The fix should really fix the problem. That number stopped corresponding to the actual number of stubs, that is why things did not compile.

Bottom line is, you can use any number of yields.

On June 7, 2016 12:30:06 PM GMT+02:00, Maximilian Csuk <notifications@github.com> wrote:
>Thank you for taking the time to look into this! :) I saw your fix, but
>does that really fix it though? What if I have more than 40 coroutine
>calls? It looks like making this number dynamic would require a lot of
>work (or not?). Is there any significant drawback to just setting this
>to a high(er) number? Like, I dunno... 500? So that the chance to run
>into this is really tiny? Because I can see myself easily surpassing 40
>coroutine calls. 
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/storm-enroute/coroutines/issues/21#issuecomment-224241557

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by IMakeGames** [comment]
Oh! Sorry, didn't realize that. Cool, I'll give it a spin!

**Comment by IMakeGames** [comment]
Working as intended in 0.7-SNAPSHOT! Thanks a lot, you're doing a really good job with with library! 😊 

As an aside: 👍  for renaming Coroutine.Frame to Coroutine.Instance.

**Comment by axel22** [comment]
No worries, and thanks! Let me know if similar issues persist.

About `Frame` - I renamed it because the name frame seems a better analogue for a method invocation frame, and a coroutine instance can have any number of frames. Glad you like this better!
