### ISSUE TITLE
Type mismatch in coroutine

### ISSUE THREAD

**Issue by smithjessk** [storm-enroute/coroutines#25]
This issue was previously in a comment on #19, but I believe it warrants its own ticket.

Note that `AsyncAwait` is as defined [here](https://github.com/smithjessk/coroutines/blob/00f77027e0011c19f60d070397bdeb9701b6bc42/coroutines-extra/src/main/scala/AsyncAwait.scala). 

```scala
test("compilation error in partial function") {
  val c: Coroutine._0[(Future[Any], AsyncAwait.Cell[Any]), Any] = coroutine { () =>
    try {
      sys.error("error")
      AsyncAwait.await(Future("ho"))
    } catch {
      case e: RuntimeException => AsyncAwait.await(Future("oh"))
      case _ => AsyncAwait.await(Future("ho"))
    }
    AsyncAwait.await(Future("oh"))
  }
  val future = AsyncAwait.async(c)
  assert(Await.result(future, 1 seconds) == "oh")
}
```

I omitted part of the stack trace, but here is the core of it:

```
[error] exception during macro expansion: 
[error] scala.reflect.macros.TypecheckException: type mismatch;
[error]  found   : Unit
[error]  required: String
[error] 	at scala.reflect.macros.contexts.Typers$$anonfun$typecheck$2$$anonfun$apply$1.apply(Typers.scala:34)

...

[error] 	at scala.reflect.macros.contexts.Context.typecheck(Context.scala:6)
[error] 	at org.coroutines.AstCanonicalization$class.canonicalizeTree(AstCanonicalization.scala:453)
[error] 	at org.coroutines.Synthesizer.canonicalizeTree(Synthesizer.scala:15)
[error] 	at org.coroutines.Synthesizer.synthesize(Synthesizer.scala:310)
[error] 	at org.coroutines.Coroutine$.synthesize(Coroutine.scala:259)
[error]     val c: Coroutine._0[(Future[Any], AsyncAwait.Cell[Any]), Any] = coroutine { () =>
```

**Comment by axel22** [comment]
Sounds like it should be a canonicalization error. I'd analyze the transformed tree.

**Comment by smithjessk** [comment]
The below tests further demonstrate the problem. I will now analyze the transformed trees.

```scala
test("this compiles") {
  val c = coroutine { () =>
    try {
      println("hello")
    } catch {
      case _: Throwable => await(Future("ho"))
    }
    await(Future("oh"))
  }
  val future = async(c)
  assert(Await.result(future, 1 seconds) == "oh")
}

test("this also compiles") {
  val c = coroutine { () =>
    try {
      await(Future("ho"))
    } catch {
      case _: Throwable => println("hello")
    }
    await(Future("oh"))
  }
  val future = async(c)
  assert(Await.result(future, 1 seconds) == "oh")
}

test("this doesn't compile") {
  val c = coroutine { () =>
    try {
      await(Future("ho"))
    } catch {
      case _: Throwable => await(Future("ho"))
    }
    await(Future("oh"))
  }
  val future = async(c)
  assert(Await.result(future, 1 seconds) == "oh")
}
```

**Comment by smithjessk** [comment]
In all three of the above tests, canonicalization generates a variable to hold the result of the try/catch block. The first two tests set the variable's type to `Any`, but the last test sets it to `String`. Presumably, this is because both the `try` and `catch` blocks return a `String`. 

I will now write a test to see if I can forcibly make the partial function have return type `Any`. This might fix the type mismatch.

**Comment by smithjessk** [comment]
I added some hacky declarations to the generated code and discovered that one of the assignments is actually reachable. I will investigate this more tomorrow.

**Comment by axel22** [comment]
Good analysis. The solution is to fix canonicalization case which says that a throw is equivalent to a `()`. A throw should be canonicalized to a throw.

Second, this line seems weird, something's missing:

```
      val matchcases =
        cases :+ cq"${pq"null"} =>" :+ cq"${pq"_"} => throw $exceptionvarname"
```

**Comment by smithjessk** [comment]
b8480aeeadbcd84b7c05da24256ecc819fd690cb changes the canonicalization of `throw` expressions.

However, `cq"${pq"null"} =>"` in `matchcases` causes another type mismatch. The right-hand side of the expression is coerced to `()`. Inside the [patten match](https://github.com/smithjessk/coroutines/blob/b8480aeeadbcd84b7c05da24256ecc819fd690cb/src/main/scala/org/coroutines/AstCanonicalization.scala#L285) case, `branchident` is also set to `()`. The canonicalization then tries to set `$localvarname = $branchident`, causing the type error.

I tried changing the mentioned case to `cq"${pq"null"} => null"`. This change passes all tests, but it does generate some warnings that say "a pure expression does nothing in statement position."

**Comment by axel22** [comment]
Can you print the match tree after canonicalization to identify where the warning comes from?

**Comment by smithjessk** [comment]
`x$macro$1` is the return value of the coroutine.
The warning occurs when we try to set `x$macro$1` equal to a `throw` expression.

```scala
(() => {
var x$macro$1 = null.asInstanceOf[Unit];
var e$macro$2: Throwable = null;
try {
  throw new scala.`package`.Exception();
  x$macro$1 = throw new scala.`package`.Exception()
} catch {
  case (t$macro$3 @ (_: Throwable)) => e$macro$2 = t$macro$3
};
```

**Comment by smithjessk** [comment]
It seems that this problem is not specific to try-catch statements. These warnings could arise in other places. We could ignore them, but that seems dirty. We could also do checks in our code generation to make sure we're not setting a `Unit`-typed variable equal to an expression that is not `()`, but that also seems dirty and over-engineered.

What are your thoughts?

**Comment by axel22** [comment]
I think that we should take small steps, and try to get as far as possible given the time frame.

- The first and the most important goal is to fix this error, which currently breaks compilation.
- After we do that, and if there are not any higher priority tasks, we can think about cleaning up warning messages. Even if we don't manage to find a solution, this is something people can still live with.

**Comment by smithjessk** [comment]
Can do! Opening a PR then.
