### ISSUE TITLE
Disallow `yieldval` calls inside `async` blocks

### ISSUE THREAD

**Issue by smithjessk** [storm-enroute/coroutines#26]
Inspired by [this discussion](https://github.com/storm-enroute/coroutines/pull/23#discussion_r68510223).

**Comment by smithjessk** [comment]
I believe 5bf908c758cfa5c909854d27b5b791f070712e78 addresses this.

**Comment by axel22** [comment]
Would be good to put into a separate PR as you originally planned, since this is orthogonal, and PRs must be kept small.

**Comment by smithjessk** [comment]
Can do! Will separate them.

**Comment by smithjessk** [comment]
[Here](https://github.com/smithjessk/coroutines/tree/disallow-yields-inside-async) is the branch.
