### ISSUE TITLE
Exposing exceptions thrown by Coroutine.Instance

### ISSUE THREAD

**Issue by smithjessk** [storm-enroute/coroutines#32]
Commit: https://github.com/storm-enroute/coroutines/commit/be3a4d82919fdb84c11aecd0efbd1585bad33e11

I think it would be useful to expose the exceptions that coroutines throw. For instance, inside [`Enumerator.next`](https://git.io/v6ID2), I could bubble up the exception thrown by the inner coroutine.

I believe that the exceptions should be exposed via a method `Coroutine.Instance.tryException`. If `hasException`, this method would return `Some($exception)`. Otherwise, it would return `None`. This is in an attempt to be in-line with the other `try` methods.

**Comment by smithjessk** [comment]
Another option would be to change the handling of exceptions inside `yieldval` calls. Currently, when the result of a coroutine is an error, then that exception is bubbled up. This behavior could be extended to when exceptions are encountered inside calls to `yieldval`. 

If this change were adopted, both tests below would pass.

```scala
// Currently passes
test("exceptions thrown in the result do bubble up") {
  val failure = coroutine { () =>
    sys.error("foo")
  }
  val c = call(failure())
  assert(!c.resume)
  assert(c.hasException)
  c.tryResult match {
    case Failure(e: Exception) => assert(e.getMessage() == "foo")
    case _ => assert(false)
  }
}

// Currently fails
test("exceptions thrown during `yieldval` should bubble up") {
  val failure = coroutine { () =>
    yieldval(sys.error("foo"))
  }
  val c = call(failure())
  assert(!c.resume)
  assert(c.hasException)
  c.tryValue match {
    case Failure(e: Exception) => assert(e.getMessage() == "foo")
    case _ => assert(false)
  }
}
```

**Comment by axel22** [comment]
`tryException` sounds like a good idea, please go ahead!

**Comment by axel22** [comment]
About your second comment, not sure I understood what is the change you have in mind.
