### ISSUE TITLE
Can't resolve coroutines-common

### ISSUE THREAD

**Issue by tlockney** [storm-enroute/coroutines#9]
I set up a minimal project with the following build.sbt contents:

```scala
scalaVersion := "2.11.7"
libraryDependencies += "com.storm-enroute" %% "coroutines" % "0.3"
```

With this I receive the following when sbt tries to pull the dependencies:

```
[info] Updating {file:/Users/Shared/Development/NikeBuild/Development/Personal/coroutines-eg/}coroutines-eg...
[info] Resolving com.storm-enroute#coroutines-common_2.11;0.3 ...
[warn]  module not found: com.storm-enroute#coroutines-common_2.11;0.3
[warn] ==== local: tried
[warn]   /Users/tlockn/.ivy2/local/com.storm-enroute/coroutines-common_2.11/0.3/ivys/ivy.xml
[warn] ==== sbt-releases-repo: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/com.storm-enroute/coroutines-common_2.11/0.3/ivys/ivy.xml
[warn] ==== sbt-plugins-repo: tried
[warn]   http://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.storm-enroute/coroutines-common_2.11/0.3/ivys/ivy.xml
[warn] ==== maven-central: tried
[warn]   http://repo1.maven.org/maven2/com/storm-enroute/coroutines-common_2.11/0.3/coroutines-common_2.11-0.3.pom
[warn] ==== Type: tried
[warn]   http://repo.typesafe.com/typesafe/maven-releases/com/storm-enroute/coroutines-common_2.11/0.3/coroutines-common_2.11-0.3.pom
[info] Resolving jline#jline;2.12.1 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.storm-enroute#coroutines-common_2.11;0.3: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Unresolved dependencies path:
[warn]          com.storm-enroute:coroutines-common_2.11:0.3 (/Users/Shared/Development/NikeBuild/Development/Personal/coroutines-eg/build.sbt#L3-5)
[warn]            +- com.storm-enroute:coroutines_2.11:0.3 (/Users/Shared/Development/NikeBuild/Development/Personal/coroutines-eg/build.sbt#L3-5)
[warn]            +- default:coroutines-eg_2.11:0.1-SNAPSHOT
[trace] Stack trace suppressed: run last *:update for the full output.
[error] (*:update) sbt.ResolveException: unresolved dependency: com.storm-enroute#coroutines-common_2.11;0.3: not found
[error] Total time: 2 s, completed Jan 2, 2016 5:59:09 PM
```

**Comment by axel22** [comment]
Ah, of course - I neglected to release the `common` subproject - will need to fix the SBT build a bit.

Will be fixed soon.

**Comment by tlockney** [comment]
Figured that was the case. Started to look at the build to check, but got distracted by other things. Thanks for the quick response. Looking forward to checking the project out. :~)

**Comment by axel22** [comment]
The commons artifact was just released to Maven - it looks like it's synced to the central repo (see link).

http://central.maven.org/maven2/com/storm-enroute/coroutines-common_2.11/0.3/

Things should work now. Thanks a lot for reporting, and sorry about the glitch!

P.S. I like your smiley :~~)

**Comment by tlockney** [comment]
Everything appears to work now. Time to dive into some coroutines!

**Comment by bracevac** [comment]
Sorry to dig this up, but could you please fix this for 0.5-SNAPSHOT, too?
Coroutines are very interesting for my own projects, so I'd love to try out 
the latest version. Cheers mate!

**Comment by axel22** [comment]
Thanks, I missed the fact that snapshot dependencies are not properly published too.

I think that the commit below should make sure that the `common` subproject is always published together with the snapshot.

https://github.com/storm-enroute/coroutines/commit/29de18c050bdd3e204b45e6555cdc570b486e036

**Comment by bracevac** [comment]
Thank you! It works.
